### PR TITLE
basic implementation for css counters

### PR DESCRIPTION
**Pull request by MicCalo**
Very basic implementation for css counters.

Short intro of css counters: [W3C Schools](https://www.w3schools.com/CSS/css_counters.asp)
Specification: [w3.org](https://www.w3.org/TR/css-lists-3/#counter-functions)

super simple counter usage test page: https://miccalo.github.io/super-duper-tribble/en-US/counter_test.html

Implemented: 

- counter-reset: counter style fixed to **decimal**
- counter-increment
- counter()

In progress:
- counter**s**()

Missing:
- counter-set
- [counter styles](https://www.w3.org/TR/css-counter-styles-3/#typedef-counter-style)

### CODE REVIEW

**Comment by tordex** [comment]
@MicCalo, please rebase your branch, there are some merge conflict. But after resolving conflicts, branch doesn't build.

**Comment by MicCalo** [comment]
Ups, I wasn't aware that I'm on your repo but thought I'm on my fork :-)

Anyway, what do you think about this in general? Any inputs?

**Comment by MicCalo** [comment]
Thanks a lot for your thoughts. I have already moved the counter stuff upwards to` litehtml::element` which avoids the casts.

Now, I'm working on adding more functionality as I think the 'whole spec' except counter types could be implemented without bloating the code base.

Regarding the `string_id` approach, I'm not sure. The strings are not predefined but can be any content. Thus a map<string, string_id> would be needed anyway and this would only benefit memory usage when the page defines multiple counter with same name. Code size and complexity would increase.

I will definitely consider writing unit tests. I have to study your approach to see if it is possible.

**Comment by tordex** [comment]
> Regarding the string_id approach, I'm not sure. The strings are not predefined but can be any content. Thus a map<string, string_id> would be needed anyway and this would only benefit memory usage when the page defines multiple counter with same name. Code size and complexity would increase.

Using ```_id(string)``` will give you ID for any string.

> I will definitely consider writing unit tests. I have to study your approach to see if it is possible.

Creating tests for litehtml is easy. Just make one or some html files with counters, to cover all/most cases of counters using and place html files into the ```test/render``` directory. Then you can build and run tests. Inside litehtml directory:
```
mkdir build
cmake ../
make
ctest
```
During the first run all new tests will be FAILED, just find the file ```your_test_file.htm.FAILED.png```, check if this PNG contains valid rendered page and rename it into ```your_test_file.htm.png```. Now running ```ctest``` will show you that all tests are passed. Add to the git both ```htm``` and ```png``` files.

Idea of tests is simple: you have html file with test and png image with correct rendering of this html page. Test just render html file with changed code and compare two images. If images are differ - the test failed.

**Comment by tordex** [comment]
Merged. Thank you for new feature!

**Pull request merged**
