### PR TITLE
fix @import

### PR DESCRIPTION
**Pull request by stasoid**
Readded #include <iso646.h> to fix Visual Studio build.

@asmaloney Did your editor silently removed utf-8 bom from media_query.cpp in a55b89f or did you do this intentionally? Because that breaks Windows build too.

### CODE REVIEW

**Comment by asmaloney** [comment]
> Readded #include <iso646.h> to fix Visual Studio build.

What errors do you get without it? That header is [not supposed to do anything](https://en.cppreference.com/w/cpp/header/ciso646) in C++ ("in a conforming implementation").

> did you do this intentionally?

Nope! Wouldn't a better solution than relying on the magic BOM be to use the utf-8 switch for MSVC?

```cmake
add_compile_options("$<$<CXX_COMPILER_ID:MSVC>:/utf-8>")
```

(I also didn't notice that the CI doesn't have a Windows build. That would be useful to add!)

**Comment by stasoid** [comment]
The error I get is the usual "'not': undeclared identifier". I get it when building litebrowser from VS2022 and when building with cmake from command line, but I just created a fresh simple project in VS and this error does not show up. I don't know what's going on.

**Comment by stasoid** [comment]
[`/permissive`](https://learn.microsoft.com/en-us/cpp/build/reference/permissive-standards-conformance?view=msvc-170) turned out to be the culprit with <iso646.h>.

**Comment by stasoid** [comment]
With `/utf-8` now [this issue](https://github.com/litehtml/litehtml/pull/333/commits/502b15c857a6354e9a034e8c38a69ceab49077c3#diff-b22bb964b4e5a6a512b17f1c6ab2c7a21f708654f164a00958dc857c090b1bd7L21) is reported as a warning. Nice.

**Comment by asmaloney** [comment]
> [/permissive](https://learn.microsoft.com/en-us/cpp/build/reference/permissive-standards-conformance?view=msvc-170) turned out to be the culprit with <iso646.h>.

I wonder if fixing the code to use standard (well, "more standard") C++ rather than making it "permissive" would be better? In all my years I've never worked on a C++ codebase [using "not" like that](https://github.com/litehtml/litehtml/blob/0a54185c8156293be6d58a59b58305aafa85e683/src/media_query.cpp#L72) :-)

There can't be that many cases?

**Comment by asmaloney** [comment]
> I use /permissive- 

Ah - I don't speak MSVC! I wouldn't have thought you'd need to use a switch to turn on standards conformance. Seems backwards.

> I used not instead of ! there to make it evident that it is overloaded

To me, this doesn't have the desired effect in this case - I have no idea what the "it" is you're referring to that's overloaded. Like I said - I've never seen C++ code use these operators and I've worked with hundreds of codebases over several decades. I just think sticking to "regular" C++ is clearer. If there's some oddity there that you want to clarify, you should add a comment.

**Pull request merged**
