### PR TITLE
Added removeChild and clearRecursive

### PR DESCRIPTION
**Pull request by bigfatbrowncat**
I've added 2 methods: 
1. <code>removeChild</code> is symmetrical to <code>appendChild</code> - it removes the item from children and clears its parent.
2. <code>clearRecursive</code> removes all children (and disconnect their parents) from the element recursively.

Both methods are very useful for dynamic DOM manipulation.

In addition I would recommend to reconsider:
1. <code>children()</code> method that returns plain list - the modification of this list could lead to an inconsistent structure (for example if someone adds an item to it without setting parent of the item), so maybe it should be a constant method returning constant link? (all manipulations would be made with additional methods)
2. Maybe <code>elements_vector</code> should be changed from <code>std::vector</code> to <code>std::list</code> - there are many use cases that add, iterate or remove items from it, but I see no cases that uses items indexes. Adding (or removing) to the middle of a vector is not quite a cheap thing...

What do you think about my ideas?

### CODE REVIEW

**Comment by bigfatbrowncat** [comment]
Do you like this modifications?

**Comment by tordex** [comment]
Sorry for delay.I'll check pull request shortly and merge it.

**Comment by bigfatbrowncat** [comment]
Thank you! I'm going to create another one soon :)

**Comment by tordex** [comment]
I've merged your pull request. Thank you. Please can you move/copy the second part (about const children() and std::list) in the Issues section? It is easier to track it there.

**Comment by bigfatbrowncat** [comment]
Done:
https://github.com/litehtml/litehtml/issues/27

**Pull request merged**
